### ISSUE TITLE
Is it possible to generate and host javadoc somewhere?

### ISSUE THREAD

**Issue by guozheng** [fangyidong/json-simple#110]
Currently, I am using the javadoc link generated by a user of SO:
http://stackoverflow.com/questions/2640309/json-simple-api-javadoc

The user hosts the javadoc on his own aws:
http://alex-public-doc.s3.amazonaws.com/json_simple-1.1/index.html

It would be great to have an official javadoc site which is updated with the code changes...

**Comment by wyxerqysan** [comment]
I just want to note that this issue has been addressed in my fork (which is fully compatible with this library). You can find more details about it here: https://cliftonlabs.github.io/json-simple/

**Comment by guozheng** [comment]
@wyxerqysan is it possible to simply host the javadoc index.html as the gh-pages index.html? This way, search engine might index it easier and it could be easier for users as well. Currently, the link to the javadoc (https://cliftonlabs.github.io/json-simple/target/apidocs/index.html) is embedded/hidden in the content and is quite hard to find.

For the user guide, maybe you can convert that to the `README.md` in your forked repo?

Thanks!

**Comment by wyxerqysan** [comment]
@guozheng thanks for the suggestion. I'll see if I can edit the content of the page to make the javadocs more obvious.

**Comment by wyxerqysan** [comment]
I've updated the website and provided a link to it in the project README.

**Comment by guozheng** [comment]
thanks a lot! 🥇
