### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jprukner** [fangyidong/json-simple#111]
Hi!
There is a

> Copyright [yyyy] [name of copyright owner] 

in LICENSE.txt
I think that [yyyy] and [name of copyright owner] should be replaced with your name and year. Am I right?

**Comment by HOYChoi** [comment]
Hello. I want to know exact year and name, too.
We're planning to use json-simple in our software, but there aren't any detailed information of copyright holder.
Would you describe it?

**Comment by jprukner** [comment]
I guess this repo is not active anymore. Closing.
